name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_secret: FIREBASE_CREDENTIALS
      - name: Install dependencies
        run: npm install
      - name: Deploy to Firebase
        run: firebase deploy
