{
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
    "predeploy": [
      "npm run build" 
    ],
    "postdeploy": [
      "echo \"Deployment successful!\"",
      "npm run test"
    ]
  },
  "functions": {
    "source": "functions",
    "predeploy": [
      "npm run build"
    ]
  },
  "database": {
    "rules": "database.rules.json"
  },
  "storage": {
    "rules": "storage.rules.json"
  }
}
